"""
Generate a SQL migration file from the current state of src/models.py.

For a project this size, the SQLAlchemy models are the single source of
truth for the schema. This script emits their CREATE TABLE statements into
a numbered file under migrations/, which migrate.py then applies and
tracks. A larger, longer-lived project would use Alembic for proper
autogenerated + hand-edited versioned migrations; that felt like more
machinery than a 5-6 hour take-home warrants, but the intent (explicit,
ordered, tracked schema changes) is the same.

Usage:
    python scripts/generate_migration.py 0001_initial
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from src.db import engine  # noqa: E402
from src.models import Base  # noqa: E402

MIGRATIONS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "migrations")


def main():
    if len(sys.argv) != 2:
        print("usage: python scripts/generate_migration.py <name, e.g. 0001_initial>")
        sys.exit(1)

    name = sys.argv[1]
    os.makedirs(MIGRATIONS_DIR, exist_ok=True)
    path = os.path.join(MIGRATIONS_DIR, f"{name}.sql")

    statements = []
    for table in Base.metadata.sorted_tables:
        statements.append(str(CreateTable(table).compile(engine)).strip() + ";")
        # CreateTable only emits the table itself. Column-level `index=True`
        # / `unique=True` (e.g. SourceFile.content_hash) are separate Index
        # objects on the table and need their own CREATE INDEX statements -
        # skipping this step would silently leave those constraints
        # unenforced in the real database despite being declared in the model.
        for index in table.indexes:
            statements.append(str(CreateIndex(index).compile(engine)).strip() + ";")

    with open(path, "w") as f:
        f.write(f"-- Generated from src/models.py by scripts/generate_migration.py\n")
        f.write("\n\n".join(statements))
        f.write("\n")

    print(f"wrote {path}")


if __name__ == "__main__":
    main()
